import type { NavigationData, NavItem } from './types.js';

const MAX_DESCRIPTION_LENGTH = 200;

function truncateDescription(text: string, maxLength: number = MAX_DESCRIPTION_LENGTH): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + '...';
}

function countTotalRepos(data: NavigationData): number {
  return data.categories.reduce((sum, cat) => sum + cat.items.length, 0);
}

function formatRepoRow(item: NavItem): string {
  const archivedMarker = item.unavailable ? '📦 ' : '';
  const name = `${archivedMarker}[${item.name}](${item.url})`;
  const description = truncateDescription(item.summary || item.description);
  const stars = `⭐ ${item.stars.toLocaleString()}`;
  return `| ${name} | ${description} | ${stars} |`;
}

function formatCategorySection(label: string, items: NavItem[]): string {
  if (items.length === 0) {
    return `### ${label}\n\n*暂无仓库*\n`;
  }

  const header = `### ${label}\n`;
  const tableHeader = '\n| Repository | Description | Stars |\n|------------|-------------|-------|';
  const rows = items.map(formatRepoRow).join('\n');

  return `${header}${tableHeader}\n${rows}`;
}

/** 将 NavigationData 转换为 Markdown 导航文档 */
export function generateReadme(data: NavigationData): string {
  const totalRepos = countTotalRepos(data);
  const categoryCount = data.categories.length;
  const timestamp = data.generated_at;

  const lines: string[] = [
    '# Claude Code Navigation',
    '',
    '> Auto-generated navigation for Claude Code ecosystem resources',
    '',
    '## Statistics',
    '',
    `- Total repositories: ${totalRepos}`,
    `- Categories: ${categoryCount}`,
    `- Last updated: ${timestamp}`,
    '',
    '## Categories',
    '',
  ];

  const categorySections = data.categories.map((cat) =>
    formatCategorySection(cat.label, cat.items)
  );

  lines.push(...categorySections);

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Auto-generated by Claude Code Navigation*');

  return lines.join('\n');
}
